name: Generate Image with Flux.1

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Промпт для генерации изображения (на английском для лучшего результата)'
        required: true
        default: 'A cute dog in a park'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate image
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PROMPT: ${{ inputs.prompt }}
        run: python src/generate_image.py

      - name: Upload generated image
        uses: actions/upload-artifact@v4
        with:
          name: image-output
          path: data/
          retention-days: 7  # Хранить 7 дней
