name: Sync to GitVerse

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitVerse
        run: |
          git config --global user.name "jimmyjonezz"
          git remote set-url origin https://jimmyjonezz:${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/jimmyjonezz/Elara_Journal.git
          git push origin main
